### ISSUE TITLE
2.6.0: bad FlatZinc generated

### ISSUE THREAD

**Issue by matsc-at-sics-se** [MiniZinc/libminizinc#555] opened 2022-03-03 09:15 UTC
```
$ cat bug.mzn
var 0..1: D;
constraint
    xorall(p in [false,true,true,false,false,false,false,D=1,false,true])(p) <-> false;
$ minizinc bug.mzn
Error: undefined identifier for type bool nc in line no. 4
Error: undefined identifier X_INTRODUCED_5_ in line no. 5
=====ERROR=====

**Comment by cyderize** [comment] 2022-03-03 09:51
I believe this is a duplicate of #551.

This will be fixed in 2.6.1 which will be released very soon.

**Closed by cyderize** 2022-03-03 09:51 UTC
