### ISSUE TITLE
show2d does not display enums names

### ISSUE THREAD

**Issue by zayenz** [MiniZinc/libminizinc#502] opened 2021-09-20 06:41 UTC
show2d displays the numeric values of enums, and not the enum names as show does. Consider the following model
```
enum Foo = {Bar, Baz};
set of Foo: s = {Bar, Baz};
array[int] of Foo: a = [Bar, Baz];
array[int, int] of Foo: m = [|
    Bar, Baz |
    Baz, Bar
|];

output [
show(s), "\n",
show(a), "\n",
show2d(m)
];
```

which has the following output
```
{Bar, Baz}
[Bar, Baz]
[| 1, 2 |
   2, 1 |]
```

Better would be to get the expected
```
{Bar, Baz}
[Bar, Baz]
[| Bar, Baz |
   Baz, Bar |]

```

**Comment by Dekker1** [comment] 2021-09-20 07:09
This is a duplicate of #238. There is actually some news on this front and this should hopefully work correctly in the next release

**Closed by Dekker1** 2021-09-20 07:09 UTC

**Comment by zayenz** [comment] 2021-09-20 15:06
Ahh, I remembered seeing something about this, but I only searched in the open issues. Thanks.

Sounds hopeful!
