### ISSUE TITLE
flatzinc crashes for a big MIP problem.

### ISSUE THREAD

**Issue by siritinga** [MiniZinc/libminizinc#81] opened 2016-01-26 16:12 UTC
Hi.

I'm trying to solve an assignment problem: given a NxN matrix, pick N elements that minimizes its sum, without repeating any row or column.

I've solved the problem with a NxN 0..1 asig matrix, to solve it efficiently with MIP, and it works fine for small problems, but when I try to use N=500, mzn2fzn seems to work, but flatzinc crashes (check using top):

./mzn-g12mip -k asig.mzn
Segmentation fault (core dumped)

It runs in a Ubuntu 14.04 with 8 GB of RAM, and it creates a 920 MB core.

I see that there is an asig.ozn file that seems to contain a representation of the solution, so may be what is crashing is the reading of this file to show the requested output format? 

Complete program:

```
int: n = 500;

array[1..n, 1..n] of var 1..1000: mat = array2d(1..n,1..n, [uniform(1,1000) | i in 1..n*n]);
array[1..n, 1..n] of var 0..1: asig;

include "globals.mzn";
constraint forall(i in 1..n)(sum(j in 1..n)(asig[i,j])=1);
constraint forall(i in 1..n)(sum(j in 1..n)(asig[j,i])=1);

var int: obj = sum(i in 1..n, j in 1..n)(mat[i,j]*asig[i,j]);
solve minimize obj;

output [show(obj)];
```

Thanks.

**Comment by guidotack** [comment] 2016-01-26 21:48
I can't reproduce the problem here.  It's not the .ozn file, it must be the MIP solver you're using. Are you running the 32 bit or 64 bit version of MiniZinc?

**Comment by siritinga** [comment] 2016-01-27 08:36
I'm running the 64 bit version.

It seems I found the problem. The default stack (8192kB) was too small. I've increased it with ulimit -s and now it works fine! 

Maybe it is possible to add a check or warning in the documentation for these cases? 

Regards.

**Comment by guidotack** [comment] 2016-01-27 21:46
Thanks, good to know.  Can you confirm it's the flatzinc process that crashes, not mzn2fzn?

**Comment by siritinga** [comment] 2016-01-28 07:15
It's flatzinc. I ran both processes separately and mzn2fzn worked fine.

I'm not at the same computer right now, so I'm speaking from memory. I executed flatzinc with an option to show some debug (-S maybe?) and with the default stack size, it showed some traces about memory used and freed, and after 3-4 traces, it crashed. 

After increasing stack size, it showed the same traces but then it showed some Cbc messages and the process completed OK, so I'm guessing it some process at the end of the first stage, or between the memory and Cbc messages, required more stack than available.

I can re-run the test and paste here the traces if that helps.

**Comment by Dekker1** [comment] 2017-10-04 06:03
This issue is being closed in a cleanup of our GitHub repository. It seems it
has been fully discussed to not be an (compiler) issue, already solved, or no
longer relevant.

If this not be the case, feel free to comment below and we'll reconsider the
issue again.

**Closed by Dekker1** 2017-10-04 06:03 UTC
