### ISSUE TITLE
2.7.5: Standard definition of all_disjoint is compiled incorrectly

### ISSUE THREAD

**Issue by informarte** [MiniZinc/libminizinc#710] opened 2023-06-19 18:57 UTC
Consider the problem `test_all_disjoint.mzn` from the intake test of the MiniZinc 2023 challenge:

```
include "globals.mzn";
array [1..3] of var set of 1..3: x :: output;
constraint all_disjoint(x);

var int: objective :: output = sum (x_i in x) (card(x_i));
solve :: set_search(x, input_order, indomain_min, complete) minimize objective;
```

Yuck neither defines `fzn_all_disjoint` nor `fzn_disjoint`, so the standard definition of `fzn_disjoint` should kick in, but it does not:

```
var set of 1..3: X_INTRODUCED_0_;
var set of 1..3: X_INTRODUCED_1_;
var set of 1..3: X_INTRODUCED_2_;
var 0..9: objective:: is_defined_var;
var 0..3: X_INTRODUCED_3_ ::var_is_introduced ;
var 0..3: X_INTRODUCED_4_ ::var_is_introduced ;
var 0..3: X_INTRODUCED_5_ ::var_is_introduced ;
array [1..3] of var set of int: x:: output_array([1..3]) = [X_INTRODUCED_0_,X_INTRODUCED_1_,X_INTRODUCED_2_];
constraint set_card(X_INTRODUCED_0_,X_INTRODUCED_3_);
constraint set_card(X_INTRODUCED_1_,X_INTRODUCED_4_);
constraint set_card(X_INTRODUCED_2_,X_INTRODUCED_5_);
constraint int_lin_eq([1,1,1,-1],[X_INTRODUCED_3_,X_INTRODUCED_4_,X_INTRODUCED_5_,objective],0):: defines_var(objective);
solve :: set_search(x,input_order,indomain_min,complete) minimize objective;
```

This issue was introduced with MiniZinc 2.7.4, MiniZinc 2.7.3 produces correct FlatZinc:

```
var set of 1..3: X_INTRODUCED_0_;
var set of 1..3: X_INTRODUCED_1_;
var set of 1..3: X_INTRODUCED_2_;
var 0..9: objective:: is_defined_var;
var 0..3: X_INTRODUCED_3_ ::var_is_introduced ;
var 0..3: X_INTRODUCED_4_ ::var_is_introduced ;
var 0..3: X_INTRODUCED_5_ ::var_is_introduced ;
var set of 1..3: X_INTRODUCED_7_ ::var_is_introduced :: is_defined_var;
var set of 1..3: X_INTRODUCED_8_ ::var_is_introduced :: is_defined_var;
var set of 1..3: X_INTRODUCED_9_ ::var_is_introduced :: is_defined_var;
array [1..3] of var set of int: x:: output_array([1..3]) = [X_INTRODUCED_0_,X_INTRODUCED_1_,X_INTRODUCED_2_];
constraint set_card(X_INTRODUCED_0_,X_INTRODUCED_3_);
constraint set_card(X_INTRODUCED_1_,X_INTRODUCED_4_);
constraint set_card(X_INTRODUCED_2_,X_INTRODUCED_5_);
constraint set_eq(X_INTRODUCED_7_,1..0);
constraint set_eq(X_INTRODUCED_8_,1..0);
constraint set_eq(X_INTRODUCED_9_,1..0);
constraint int_lin_eq([1,1,1,-1],[X_INTRODUCED_3_,X_INTRODUCED_4_,X_INTRODUCED_5_,objective],0):: defines_var(objective);
constraint set_intersect(X_INTRODUCED_0_,X_INTRODUCED_1_,X_INTRODUCED_7_):: defines_var(X_INTRODUCED_7_);
constraint set_intersect(X_INTRODUCED_0_,X_INTRODUCED_2_,X_INTRODUCED_8_):: defines_var(X_INTRODUCED_8_);
constraint set_intersect(X_INTRODUCED_1_,X_INTRODUCED_2_,X_INTRODUCED_9_):: defines_var(X_INTRODUCED_9_);
solve :: set_search(x,input_order,indomain_min,complete) minimize objective;
```

**Comment by Dekker1** [comment] 2023-06-19 21:48
Duplicate of #707

**Closed** 2023-06-19 21:48 UTC
