### ISSUE TITLE
bool2int applied to a vector

### ISSUE THREAD

**Issue by krzku** [MiniZinc/libminizinc#231] opened 2018-08-29 10:18 UTC
In the challenge benchmark steiner_tree the compiler generates the following solve declaration

solve :: seq_search([int_search(bool2int([es[20],es[15],es[9],es[7],es[14],es[13],es[11],es[1],es[5],es[10],es[16],es[6],es[19],es[17],es[12],es[3],es[4],es[2],es[8],es[18],vs[1],vs[4],vs[5],vs[13],vs[16],vs[7],vs[2],vs[15],vs[8],vs[10],vs[14],vs[6],vs[17],vs[12],vs[11],vs[9],vs[3]]),input_order,indomain_min,complete),int_search([root],input_order,indomain_min,complete)]) minimize objective;

where constraint bool2int is applied to a vector. I do not recall that this is a correct flatzinc. At least Gecode and JaCoP do not accept it. Chuffed indicate type error i search annotation and ignores it.

/Kris

**Comment by guidotack** [comment] 2018-08-30 09:26
This is a duplicate of #226 and already fixed, the fix will be available in the 2.2.1 release early next week.

**Closed by guidotack** 2018-08-30 09:26 UTC
Labels: duplicate
