### ISSUE TITLE
"fzn-gecode.exe - Entry Point Not Found" when integrating with python

### ISSUE THREAD

**Issue by mushfiqur11** [MiniZinc/libminizinc#309] opened 2019-08-09 13:42 UTC
I tried to integrate MiniZinc models with python. I used different libraries for it - "pymzn", "iminizinc", "minizinc" etc. I installed these using the pip installer from the anaconda command prompt. But in every case, there is an error with heading "fzn-gecode.exe - Entry Point Not Found". The body of the error says "The procedure entry point ??6?$QVector@VQPointF@@@@QEAAAEAV0@$$QEAVQPointF@@@Z could not be located in the dynamic link library C:\MiniZinc\bin\fzn-gecode.exe."

**Comment by schutta** [comment] 2019-10-06 23:13
I have the same issue that when running MiniZinc 2.3.2 in command line prompt under Windows, but, interestingly, it works when running via MiniZinc IDE.

This issue seems to be appearing with MiniZinc 2.3.x, because MiniZinc 2.2.3 works fine in this case.

**Comment by sarafrim** [comment] 2019-10-22 07:31
I'm having the same problem. If I have Python 3.7 as the active environment (using anaconda), it works fine, but if I use the Python 3.6 or 3.5 environments I get the same error message as you describe. Had no problem in MiniZinc 2.2.2.

**Comment by Dekker1** [comment] 2019-10-23 01:09
The issue that you are running into stems from the execution environment in which you run the fzn-gecode. The Gecode version shipped with MiniZinc depends on the Qt framework. This allows people to use Gist to display their search trees. The downside of this is that we need to ensure that Gecode has access to Qt whenever it is started, even when it doesn't use Gist. The error that your seeing is exactly that: it cannot find Qt when the fzn-gecode executable is started.

On Windows dynamic libraries are located using the PATH environment variable and the current directory (https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order). Adding both the folder in which MiniZinc is installed and the "bin/" folder that is inside this directory should solve the problem. (The Qt libraries are installed in the main directory. fzn-gecode is located in the bin/ folder.) In the case of Python, it sounds like the versions other than 3.7 are changing your environment variables. You could try and output the PATH environment variable to ensure that the correct folders are on the PATH:

```python
import os
print(os.environ['PATH'])
```

This issue is caused by a change made in MiniZinc 2.3.0 were we moved fzn-gecode to the "bin/" folder to have consistent and exact solver configurations between different operating systems.

**Comment by schutta** [comment] 2019-10-24 22:53
MiniZinc IDE 2.3.2 is now working on my machine, but not in the way Jip suggested.

Since I had MiniZinc IDE 2.2.3 installed on my system, I installed the new version first, but I recognised that it was not a clean installation, e.g., the fzn-gecode.exe from 2.2.3 was still in the MiniZinc folder. Due to that, I uninstalled MiniZinc IDE, which deleted the entire MiniZinc folder, and installed 2.3.2. After that it was working fine for me.

@mushfiqur11 and @sarafrim: Does an uninstall of MiniZinc IDE and then an install of the latest version solve the issue for you?

**Comment by schutta** [comment] 2019-10-24 22:56
PS: It also runs fine for me via Python 3.6 Environment (Anaconda with Python 3.7 is installed on my system, but I run the Python script in Python 3.6 environment).

**Comment by sarafrim** [comment] 2019-10-28 09:29
Thanks for the suggestions @Dekker1 and @schutta. I tried both uninstalling the MiniZinc IDE and then reinstalling it, and adding the "bin/"-folder into the PATH environmant variables, but neither worked. 

If I follow Jip's suggestion to see the PATH environment variables within the Python environment,  either environment containts the correct paths (C:\Program Files\MiniZinc; C:\Program Files\MiniZinc\bin;). I don't know if it's because Python 3.7 is my default Anaconda environment, but as soon as I switch to another environment, I can't run MiniZinc from the console.

**Comment by mushfiqur11** [comment] 2019-10-28 09:32
I switched to linux from windows and it worked for me perfectly. I don't know what exactly caused the issue in the first place.

**Comment by mushfiqur11** [comment] 2019-10-28 09:33
@schutta I tried uninstalling MiniZinc IDE. It didn't work.

**Comment by guidotack** [comment] 2019-10-29 01:53
Can you please confirm whether there is still an `fzn-gecode.exe` binary in the `C:\Program Files\MiniZinc` directory? There should only be one in the `C:\Program Files\MiniZinc\bin` directory, but not the one above that.

**Comment by sarafrim** [comment] 2019-10-29 08:00
No, there is no fzn-gecode.exe in the main directory, only in the bin folder.

**Comment by Dekker1** [comment] 2019-10-30 04:27
The problem could be caused by another version of Qt conflicting with the version of Qt included by MiniZinc. As you say different versions of Python give you different results, it might be that some of the versions of Python include a version of Qt for PyQt, while the others don't. 

You can try to ensure that the directory from which Python is loaded is after the MiniZinc directory on the PATH.

**Comment by guidotack** [comment] 2019-11-27 21:43
This issue will be fixed in the next release, when the fzn-gecode binary won't be linked against Qt any longer.

**Closed by guidotack** 2019-11-27 21:43 UTC
