### ISSUE TITLE
2.7.3: Cannot solve cutstock example

### ISSUE THREAD

**Issue by informarte** [MiniZinc/libminizinc#686] opened 2023-04-28 16:06 UTC
MiniZinc 2.7.3 fails to solve the  [`cutstock` problem](https://github.com/MiniZinc/libminizinc/files/11355315/cutstock.mzn.gz) from the old MiniZinc examples.

MiniZinc 2.7.2 computes this solution in no time:

```
Cost = 4
Pieces = 
	[1, 1, 1, 1, 0, 0, 0, 0]
Items = 
	0 1 1 0 0 0 0 0
	0 0 0 2 0 0 0 0
	3 0 1 0 0 0 0 0
	
----------
==========
```

MiniZinc 2.7.3, however, cannot solve this problem.

Comparing the FlatZinc produced by 2.7.2 to that from 2.7.3, it turns out that 2.7.3 produces less constraints than 2.7.2:

```
< constraint int_le(0,X_INTRODUCED_8_);
< constraint int_le(0,X_INTRODUCED_9_);
< constraint int_le(0,X_INTRODUCED_10_);
< constraint int_le(0,X_INTRODUCED_11_);
< constraint int_le(0,X_INTRODUCED_12_);
< constraint int_le(0,X_INTRODUCED_13_);
< constraint int_le(0,X_INTRODUCED_14_);
< constraint int_le(0,X_INTRODUCED_15_);
< constraint int_le(0,X_INTRODUCED_16_);
< constraint int_le(0,X_INTRODUCED_17_);
< constraint int_le(0,X_INTRODUCED_18_);
< constraint int_le(0,X_INTRODUCED_19_);
< constraint int_le(0,X_INTRODUCED_20_);
< constraint int_le(0,X_INTRODUCED_21_);
< constraint int_le(0,X_INTRODUCED_22_);
< constraint int_le(0,X_INTRODUCED_23_);
< constraint int_le(0,X_INTRODUCED_24_);
< constraint int_le(0,X_INTRODUCED_25_);
< constraint int_le(0,X_INTRODUCED_26_);
< constraint int_le(0,X_INTRODUCED_27_);
< constraint int_le(0,X_INTRODUCED_28_);
< constraint int_le(0,X_INTRODUCED_29_);
< constraint int_le(0,X_INTRODUCED_30_);
< constraint int_le(0,X_INTRODUCED_31_);
```

**Comment by Dekker1** [comment] 2023-05-01 02:51
This is a duplicate of #684. I'm pushing a fix soon.

**Closed by Dekker1** 2023-05-01 02:51 UTC
