### ISSUE TITLE
mzn-cbc giving inconsistent output with json file input

### ISSUE THREAD

**Issue by Strider26** [MiniZinc/libminizinc#209] opened 2018-04-19 07:23 UTC
I have a minizinc model which takes .json input file dynamically created by python code.
Strangely the same command line code gives "Unsatisfiable" output but when I rerun the code it gives me the expected optimal output.

`mzn-cbc --output-mode json -Glinear Prod.mzn InputData.json`

I have no clue how to debug this. The main program is in python which calls above command from subprocess. 
I have tried the same command from command prompt as well (Windows) it gives the same inconsistent result.

**Comment by Dekker1** [comment] 2018-04-19 07:26
Hi @Strider26,

We've recently fixed a problem within the MiniZinc JSON parser that occurred on multi-digit numbers. I think this is probably the cause of your problem. The problem should be resolved in the next release.

**Comment by Strider26** [comment] 2018-05-11 08:45
Hi @Dekker1 ,

Is there a way I could write json object in python to .dzn file as a workaround for this.
TIA.

**Comment by Dekker1** [comment] 2018-05-14 09:57
@Strider26, The best solution would be to compile the development branch and see if that solves your problem.

**Comment by guidotack** [comment] 2018-08-25 01:15
This should be fixed in the current release.

**Closed by guidotack** 2018-08-25 01:15 UTC
Labels: bug
