### ISSUE TITLE
MZN 2.4.1: bug with logical operations

### ISSUE THREAD

**Issue by matsc-at-sics-se** [MiniZinc/libminizinc#390] opened 2020-05-16 13:19 UTC
MiniZinc says `WARNING: model inconsistency detected` on this:
```
var bool: p;
constraint
    not(((false /\ true) \/ p));
solve satisfy;
```
even though the constraint is true for `p = false`.

**Comment by a1880** [comment] 2020-05-17 11:57
This Warning is not issued in my MiniZinc 2.4.3 installation under Windows.

**Comment by cyderize** [comment] 2020-05-17 22:27
This is a duplicate of #359 and was fixed in version 2.4.2.

**Closed by cyderize** 2020-05-17 22:27 UTC
