### ISSUE TITLE
Error: Gecode: Float::linear: Number out of limits

### ISSUE THREAD

**Issue by lalithsuresh** [MiniZinc/libminizinc#246] opened 2018-10-05 15:26 UTC
I have a model where my objective function is a combination of floats and it triggers the following error:  `Error: Gecode: Float::linear: Number out of limits`. 

Here's a simplified version of the model to reproduce the bug. hostCost in this example could very well be an integer instead, but my actual model requires 'hostCost' to be a float.

```
int: numVms = 3;
array[1..numVms] of int : vmId = [1, 2, 3];
array[1..numVms] of var int : vmHost;
array[1..numVms] of int : vmRequest = [1, 1, 1];

int: numHosts = 3;
array[1..numHosts] of int : hostId = [1, 2, 3];
array[1..numHosts] of int : hostCapacity = [3, 3, 3];

array[1..numHosts] of var float : hostCost = 
            [hostCapacity[host] - sum([vmRequest[v] | h in 1..numHosts, v in 1..numVms where vmHost[v] == hostId[h]   /\ hostId[h] == hostId[host]]) | host in hostId];
                                              
solve maximize min(hostCost) - max(hostCost);
```

**Comment by Dekker1** [comment] 2018-10-05 23:47
Hi @lalithsuresh,

I'm afraid this isn't a problem within MiniZinc, but rather a limitation of the Gecode solver. Gecode is a constraint programming based solver, which are often limited in their support for floating point variables. Gecode has a limitation to which values floating point values can take.

The easiest way to solve your problem might be to switch to a different solver. MIP based solvers, like cbc, scip, gurobi, or cplex, offer more support for floating point variables and might thus be a better fit for your model.

If you believe the model is running into the Gecode limitation by mistake, then I would suggest you post your issue in the Gecode repository: https://github.com/Gecode/gecode

**Comment by chschulte** [comment] 2018-10-06 11:01
Well, I would disagree with what @Dekker1 says: MiniZinc does not use the solver the right way ;-) Anyway, the problem is that you use a float variable with a too big domain, it should work if you put some limits yourself on the hostCost variables and only then post the constraints on them.

This is not a bug in Gecode, it is the intended behavior.

**Comment by lalithsuresh** [comment] 2018-10-06 17:27
Thanks @chschulte. Even the following code with bounds specified triggers the same bug, so I suspect the bounds are not being communicated to Geocode.

```
int: numVms = 3;
array[1..numVms] of int : vmId = [1, 2, 3];
array[1..numVms] of var int : vmHost;
array[1..numVms] of int : vmRequest = [1, 1, 1];


int: numHosts = 3;
array[1..numHosts] of int : hostId = [1, 2, 3];
array[1..numHosts] of int : hostCapacity = [3, 3, 3];


array[1..numHosts] of var -100.0..1000.0 : hostCost =
            [hostCapacity[host] - sum([vmRequest[v] | h in 1..numHosts, v in 1..numVms where vmHost[v] == hostId[h]   /\ hostId[h] == hostId[host]]) | host in hostId];

var -1000..1000.0: minCost = min(hostCost);
var -1000..1000.0: maxCost = max(hostCost);
solve maximize minCost - maxCost;
```

**Comment by chschulte** [comment] 2018-10-09 10:03
This is really strange... Can one of the MiniZinc people have a look here?

**Comment by lalithsuresh** [comment] 2018-10-09 15:02
@Dekker1: is my example above the right way to force bounds on hostCost? Because we're still running into the same issue.

**Comment by Dekker1** [comment] 2018-10-10 00:01
Hi @lalithsuresh and @chschulte,

I'm sorry that I might have overlooked the actual problem. I had just assumed it was a model for which no tight bounds could be provided.  Since I have some university work to deal with I've asked Alex to look into it on Monday, but I'm unaware how far he got on the problem.

I had a quick run of the models in this issue and they just seems to work though. I'm running the models on the newest release MiniZinc version (2.2.1) and with the following command: `minizinc --solver gecode -a float.mzn`. (The IDE seems to report the same)

@lalithsuresh, can you provide more information on the system that your using (OS, MiniZinc version, what command you run) so we can reproduce the issue?

**Comment by lalithsuresh** [comment] 2018-10-10 16:39
Hi @Dekker1 . The problem disappears when I switch to minizinc 2.2.1. I was on 2.2.0 before.

**Comment by Dekker1** [comment] 2018-10-10 16:41
I'm glad to hear the problem is then solved. I assume this issue must have been a duplicate of #225.

**Closed by Dekker1** 2018-10-10 16:41 UTC
