### ISSUE TITLE
max(array [$U] of $T) returns var if $T is optional

### ISSUE THREAD

**Issue by CervEdin** [MiniZinc/libminizinc#848] opened 2024-09-17 10:40 UTC
It seems `function $T: max(array [$U] of $T: x)` doesn't work properly for optional types.

Calling `max` on `[<>, 1]` returns `var int` but I would've expected `opt int`.

```zinc
array[int] of opt int: X = [<>, 1];
opt int: x = max(X);
```

```text
type error: initialisation value for `x' has invalid type-inst: expected `opt int', actual `var int'
```

Seen on
```text
MiniZinc to FlatZinc converter, version 2.8.5, build 1315240962
Copyright (C) 2014-2024 Monash University, NICTA, Data61
```

What I expect is something along the lines of
```zinc
array[int] of opt int: X = [<>];
opt int: x = if exists(e in X) (occurs(e)) then fix(max(X)) else <> endif;
```
except an exception if `X` is empty.

**Comment by guidotack** [comment] 2024-09-17 12:05
This is due to a missing definition of the optional version of `min` and `max` in the library. The expected behaviour is different though, `min` and `max` on optional arrays ignore all absent values and are undefined if all elements of the array are absent. For the version that returns absent, you need to use the `min_weak` or `max_weak` functions.
A fix for this will be added to the next release.

**Closed** 2024-09-25 23:46 UTC
Labels: bug, resolved
