### ISSUE TITLE
mzn2fzn 2.2.0 emits garbage solve goals

### ISSUE THREAD

**Issue by informarte** [MiniZinc/libminizinc#235] opened 2018-09-04 15:40 UTC
For some problems from the MiniZinc benchmarks library, mzn2fzn 2.2.0 emits garbage solve goals. There are two types of issues:

 1. Solve goals with undefined variables
 2. Solve goals with syntax errors

This first issue affects the following problems: carpet-cutting, cyclic-rcpsp, crosswords, flexible-jobshop

For example, for carpet-cutting we get:

```solve :: seq_search([fix_ori_0_or_180,fix_ori_0_or_90,fix_yx,fix_rl]) minimize RollLen;```

but ```fix_ori_0_or_180``` is undefined.

The second issue affects the following problems: triangular, opt_cryptanalysis_r5, rel2onto, routing-flexible

For example, for triangular we get:

```solve :: int_search([heart[i,j] | i in N, j in 1..i, ],input_order,indomain_max,complete) maximize objective;```

**Comment by guidotack** [comment] 2018-09-05 07:28
This is a duplicate of #226 and already fixed, the fix is available in the 2.2.1 release (sources available now, binaries coming in the next couple of days).

**Comment by informarte** [comment] 2018-09-05 09:46
The issue is not fully fixed; for routing-flexible, mzn2fzn 2.2.0 emits the following solve goal:

```solve :: seq_search([int_search(X_INTRODUCED_5108_,input_order,indomain_split,complete),int_search(X_INTRODUCED_5107_,input_order,indomain_split,complete),int_search(X_INTRODUCED_5106_,input_order,indomain_split,complete),int_search(X_INTRODUCED_5105_,input_order,indomain_split,complete),int_search(X_INTRODUCED_5104_,input_order,indomain_split,complete),int_search(fLastLeg,input_order,indomain_split,complete)]):: mzn_rhs_from_assignment minimize objective;```

```mzn_rhs_from_assignment``` is both undefined and not a proper search annotation.

**Comment by guidotack** [comment] 2018-09-05 09:58
Thanks, this one is actually an unrelated bug. It's an internal annotation (and as such any solver should simply ignore it as for any unknown annotation), but it should have been removed during flattening. I'll add a hot fix to the 2.2.1 branch.

**Closed** 2018-09-05 10:30 UTC
