### ISSUE TITLE
Disappearing redefinitions of linear constraints

### ISSUE THREAD

**Issue by nickd4** [MiniZinc/libminizinc#112] opened 2016-08-24 03:18 UTC
I notice that 2.0.13 changelog lists the following entry:
"Fix a bug in the Common Subexpression Elimination table of the compiler, which could lead to some constraints being dropped (especially when using linear redefinitions)."

We still seem to have a problem like this, as of 2.0.14. I'm trying to run Opturion CPX using Minizinc 2.0 as the frontend/compiler, but the mznlib from Opturion CPX does not work properly with new Minizinc.

It seems Opturion CPX relies on translating constraints like int_ne_reif to int_lin_ne_reif, which is a sensible thing to do (I tried doing the same in my own work earlier this year, but gave up due to the same strange translation issues, and ended up just putting the same translation in my Flatzinc solver binary instead of doing it in Minizinc).

I have checked into this problem and discovered it's a regression Minizinc 2.0.8 -> 2.0.9. I have attached the necessary files to duplicate the issue. When the issue occurs (with Minizinc 2.0.9), the generated Flatzinc is significantly shorter and does not contain the int_lin_ne_reif constraints or the variables associated with them. So it just defines a trivial grid colouring problem where all cells can be set to 1 and the objective comes out as 1. When the issue does not occur (with Minizinc 2.0.8) the generated Flatzinc has "int_lin_ne_reif" constraints in it and solves correctly with Opturion CPX.

[int_lin_ne_reif_issue.zip](https://github.com/MiniZinc/libminizinc/files/433969/int_lin_ne_reif_issue.zip)

**Comment by guidotack** [comment] 2016-08-25 06:56
The issue seems to be bool_clause_reif and array_bool_or rather than int_ne_reif.  The problem is that the compiler rewrites a reified clause into an array_bool_or internally, and then array_bool_or is redefined in terms of bool_clause_reif, which messes up the CSE table.  In essence, you're not allowed to create any cyclic redefinitions, and this one is cyclic because of an internal assumption made by the compiler. The correct way to deal with it would be to call the CPX builtin cpx_bool_clause_reif, and rewrite both bool_clause_reif and array_bool_or into this builtin.

**Comment by Dekker1** [comment] 2017-10-04 06:24
This issue is being closed in a cleanup of our GitHub repository. It seems it
has been fully discussed to not be an (compiler) issue, already solved, or no
longer relevant.

If this not be the case, feel free to comment below and we'll reconsider the
issue again.

**Closed by Dekker1** 2017-10-04 06:24 UTC
