### ISSUE TITLE
MiniZinc 2.2.3: -O2, -O3, ... not working

### ISSUE THREAD

**Issue by matsc-at-sics-se** [MiniZinc/libminizinc#264] opened 2018-11-27 11:12 UTC
Symptom:

```
$ mzn-chuffed -O3 -a -s --fzn-flag -f --fzn-flag --rnd-seed --fzn-flag 123456 -t 600000 -D good_cumulative=true -D good_diffn=false -D good_member=false pegwit.ec_crypt.cpDecodeSecret.mzn pegwit.ec_crypt.cpDecodeSecret.dzn
Generated FlatZinc statistics:
Paths: 8504
Variables: 2229 bool, 2335 int
Constraints: 1155 bool, 4620 int
    This is a minimization problem.
WARNING: the --time-out flag has recently been changed.The time-out is now provided in milliseconds instead of seconds
/builds/minizinc/vendor/build/chuffed/chuffed/vars/int-var.cpp:116: Cannot initialise vals in unbounded IntVar
=====ERROR=====
matsc@teterev:~/zapbar10/unison-int/run-Mips1$ mzn-chuffed -O2 -a -s --fzn-flag -f --fzn-flag --rnd-seed --fzn-flag 123456 -t 600000 -D good_cumulative=true -D good_diffn=false -D good_member=false pegwit.ec_crypt.cpDecodeSecret.mzn pegwit.ec_crypt.cpDecodeSecret.dzn
Generated FlatZinc statistics:
Paths: 440616
Variables: 2362 bool, 2533 int
Constraints: 1220 bool, 4889 int
    This is a minimization problem.
WARNING: the --time-out flag has recently been changed.The time-out is now provided in milliseconds instead of seconds
/builds/minizinc/vendor/build/chuffed/chuffed/vars/int-var.cpp:116: Cannot initialise vals in unbounded IntVar
=====ERROR=====
```

Also, with `-O2`, `minizinc` grabs some 10 GB of memory on this instance, with really is a "hello world" example.  Larger instances, with `-O2`, simply bring my computer to a grinding halt.

[bug.zip](https://github.com/MiniZinc/libminizinc/files/2619617/bug.zip)

**Comment by guidotack** [comment] 2019-11-27 22:13
This seems to have been fixed somewhere along the way (can't reproduce with current develop build). I'll close the issue, if it still doesn't work for you please re-open it.

**Closed by guidotack** 2019-11-27 22:13 UTC
