### ISSUE TITLE
Syntax error when using identifier "b" in enums

### ISSUE THREAD

**Issue by GonzaloHernandez** [MiniZinc/libminizinc#736] opened 2023-10-17 05:31 UTC
I came across another error when I try to define an enumeration using an identifier "b" in lowercase.  The following example generates the error.
```
enum b = {Mary,Dylan,Jhon};
```
MiniZinc reports the following message:
```
MiniZinc: type error: type-inst must be par set but is `bool'
Process finished with non-zero exit code 1.
```
Thanks again team.

**Comment by cyderize** [comment] 2023-10-17 05:38
This is a duplicate of #726 and will be fixed in the next release

**Closed by cyderize** 2023-10-17 05:38 UTC
