### ISSUE TITLE
Warm-starting example does not compile

### ISSUE THREAD

**Issue by informarte** [MiniZinc/libminizinc#579] opened 2022-05-04 07:34 UTC
Section 2.5.5 of the MiniZinc handbook given a warm-starting example, but it does not compile:

```
Error: type error: no function or predicate with this signature found: `warm_start(array[int] of var float,array[int] of opt float)'
Cannot use the following functions or predicates with the same identifier:
annotation warm_start(array [int] of var set of int: x,array [int] of set of int: v);
    (argument 1 expects type array[int] of var set of int, but type array[int] of var float given)
    (argument 2 expects type array[int] of set of int, but type array[int] of opt float given)
annotation warm_start(array [int] of var bool: x,array [int] of bool: v);
    (argument 1 expects type array[int] of var bool, but type array[int] of var float given)
    (argument 2 expects type array[int] of bool, but type array[int] of opt float given)
annotation warm_start(array [int] of var int: x,array [int] of int: v);
    (argument 1 expects type array[int] of var int, but type array[int] of var float given)
    (argument 2 expects type array[int] of int, but type array[int] of opt float given)
annotation warm_start(array [int] of var float: x,array [int] of float: v);
    (argument 2 expects type array[int] of float, but type array[int] of opt float given)
```

**Comment by cyderize** [comment] 2022-05-04 08:29
Duplicate of #567

**Closed by cyderize** 2022-05-04 08:29 UTC
