### ISSUE TITLE
all_disjoint from 2.6.4 to 2.7.5 : different fzn file

### ISSUE THREAD

**Issue by cprudhom** [MiniZinc/libminizinc#707] opened 2023-06-16 14:54 UTC
Hi there

I migrated MiniZincIDE from 2.6.4 to 2.7.5 (and therefore libminizinc too) and was surprised to see that some constraints were missing after transforming the model into flatzinc, with choco as the backend solver.

Input MiniZinc model:
```mzn
include "globals.mzn";
array [1..3] of var set of 1..3: x :: output;
constraint all_disjoint(x);

var int: objective :: output = sum (x_i in x) (card(x_i));
solve :: set_search(x, input_order, indomain_min, complete) minimize objective;
```

is turned into this file with 2.6.4:
```fzn
var set of 1..3: X_INTRODUCED_0_;
var set of 1..3: X_INTRODUCED_1_;
var set of 1..3: X_INTRODUCED_2_;
var 0..9: objective:: is_defined_var;
var 0..3: X_INTRODUCED_3_ ::var_is_introduced ;
var 0..3: X_INTRODUCED_4_ ::var_is_introduced ;
var 0..3: X_INTRODUCED_5_ ::var_is_introduced ;
var set of 1..3: X_INTRODUCED_7_ ::var_is_introduced :: is_defined_var;
var set of 1..3: X_INTRODUCED_8_ ::var_is_introduced :: is_defined_var;
var set of 1..3: X_INTRODUCED_9_ ::var_is_introduced :: is_defined_var;
array [1..3] of var set of int: x:: output_array([1..3]) = [X_INTRODUCED_0_,X_INTRODUCED_1_,X_INTRODUCED_2_];
constraint set_card(X_INTRODUCED_0_,X_INTRODUCED_3_);
constraint set_card(X_INTRODUCED_1_,X_INTRODUCED_4_);
constraint set_card(X_INTRODUCED_2_,X_INTRODUCED_5_);
constraint set_eq(X_INTRODUCED_7_,1..0);
constraint set_eq(X_INTRODUCED_8_,1..0);
constraint set_eq(X_INTRODUCED_9_,1..0);
constraint int_lin_eq([1,1,1,-1],[X_INTRODUCED_3_,X_INTRODUCED_4_,X_INTRODUCED_5_,objective],0):: defines_var(objective);
constraint set_intersect(X_INTRODUCED_0_,X_INTRODUCED_1_,X_INTRODUCED_7_):: defines_var(X_INTRODUCED_7_);
constraint set_intersect(X_INTRODUCED_0_,X_INTRODUCED_2_,X_INTRODUCED_8_):: defines_var(X_INTRODUCED_8_);
constraint set_intersect(X_INTRODUCED_1_,X_INTRODUCED_2_,X_INTRODUCED_9_):: defines_var(X_INTRODUCED_9_);
solve :: set_search(x,input_order,indomain_min,complete) minimize objective;
```

and into this with 2.7.5:
```fzn
var set of 1..3: X_INTRODUCED_0_;
var set of 1..3: X_INTRODUCED_1_;
var set of 1..3: X_INTRODUCED_2_;
var 0..9: objective:: is_defined_var;
var 0..3: X_INTRODUCED_3_ ::var_is_introduced ;
var 0..3: X_INTRODUCED_4_ ::var_is_introduced ;
var 0..3: X_INTRODUCED_5_ ::var_is_introduced ;
array [1..3] of var set of int: x:: output_array([1..3]) = [X_INTRODUCED_0_,X_INTRODUCED_1_,X_INTRODUCED_2_];
constraint set_card(X_INTRODUCED_0_,X_INTRODUCED_3_);
constraint set_card(X_INTRODUCED_1_,X_INTRODUCED_4_);
constraint set_card(X_INTRODUCED_2_,X_INTRODUCED_5_);
constraint int_lin_eq([1,1,1,-1],[X_INTRODUCED_3_,X_INTRODUCED_4_,X_INTRODUCED_5_,objective],0):: defines_var(objective);
solve :: set_search(x,input_order,indomain_min,complete) minimize objective;
```
which is not correct anymore.

I discovered that I could declare the all_disjoint constraint, but it wasn't obvious.  Setting the compilation to "vebose" mode wasn't very useful.

Could I have been informed by reading the ChangeLogs (which I admit I don't always read carefully)? 

Thank you for your answers

**Comment by cyderize** [comment] 2023-06-19 00:27
This bug seems to have been already fixed in the current `develop` branch. Now the following FlatZinc is produced:

```
var set of 1..3: X_INTRODUCED_0_;
var set of 1..3: X_INTRODUCED_1_;
var set of 1..3: X_INTRODUCED_2_;
var 0..9: objective:: is_defined_var;
var 0..3: X_INTRODUCED_3_ ::var_is_introduced ;
var 0..3: X_INTRODUCED_4_ ::var_is_introduced ;
var 0..3: X_INTRODUCED_5_ ::var_is_introduced ;
array [1..3] of var set of int: x:: output_array([1..3]) = [X_INTRODUCED_0_,X_INTRODUCED_1_,X_INTRODUCED_2_];
constraint set_card(X_INTRODUCED_0_,X_INTRODUCED_3_);
constraint set_card(X_INTRODUCED_1_,X_INTRODUCED_4_);
constraint set_card(X_INTRODUCED_2_,X_INTRODUCED_5_);
constraint set_intersect(X_INTRODUCED_0_,X_INTRODUCED_1_,1..0);
constraint set_intersect(X_INTRODUCED_0_,X_INTRODUCED_2_,1..0);
constraint set_intersect(X_INTRODUCED_1_,X_INTRODUCED_2_,1..0);
constraint int_lin_eq([1,1,1,-1],[X_INTRODUCED_3_,X_INTRODUCED_4_,X_INTRODUCED_5_,objective],0):: defines_var(objective);
solve :: set_search(x,input_order,indomain_min,complete) minimize objective;
```

**Comment by Dekker1** [comment] 2023-06-19 00:31
This is a duplicate of #700

**Closed** 2023-06-21 03:38 UTC
Labels: bug, resolved
