### ISSUE TITLE
Linear library: can't flatten variable `if-then-else` expression

### ISSUE THREAD

**Issue by dimbleby** [MiniZinc/libminizinc#73] opened 2016-01-04 20:10 UTC
This [gist](https://gist.github.com/dimbleby/cc356023e3b021a1cd28) contains some logic related to the 'gang warfare' problem in the recent Coursera modeling-with-minizinc course.

(I've removed as much useful logic as I can while reproducing the issue, and I'll be happy to remove this gist when we're done with it).

Flattening using the `linear` library results in the following error:
```
MiniZinc: flattening error:
  /usr/local/Cellar/minizinc/2.1.6/bin/../share/minizinc/linear/redefs_lin_reifs.mzn:198:
  in if-then-else expression
  /usr/local/Cellar/minizinc/2.1.6/bin/../share/minizinc/linear/redefs_lin_reifs.mzn:203:
  in call 'aux_int_eq_iff_1'
  /usr/local/Cellar/minizinc/2.1.6/bin/../share/minizinc/linear/redefs_lin_reifs.mzn:369:
  in if-then-else expression
  /usr/local/Cellar/minizinc/2.1.6/bin/../share/minizinc/linear/redefs_lin_reifs.mzn:376:
  in let expression
  /usr/local/Cellar/minizinc/2.1.6/bin/../share/minizinc/linear/redefs_lin_reifs.mzn:378:
  in binary '/\' operator expression
  in call 'aux_int_le_if_1'
  /usr/local/Cellar/minizinc/2.1.6/bin/../share/minizinc/linear/redefs_lin_halfreifs.mzn:80:
  in call 'aux_int_le_zero_if_0'
  /usr/local/Cellar/minizinc/2.1.6/bin/../share/minizinc/linear/redefs_lin_halfreifs.mzn:33:
  in if-then-else expression
  /usr/local/Cellar/minizinc/2.1.6/bin/../share/minizinc/linear/redefs_lin_halfreifs.mzn:42:
  in binary '<=' operator expression
  in binary '*' operator expression
  unbounded coefficient in linear expression
```
-- `mzn2fzn -G linear gang.mzn`

**Comment by skosch** [comment] 2016-05-04 03:32
I've run into similar errors with `aux_int_le_zero_if_0` and `ub(x)` being unbounded – in my case it was via using `abs` in the mzn. It can lead to all kinds of nasty errors, from the above, to `MiniZinc: internal error: sDomain.checkFiniteBounds()`, to CBC asserts failing silently, to totally random crashes.

It would be great if someone could shed some light on this – my (admittedly cursory) search for the root cause hasn't led anywhere, particularly because the starting conditions have to be just right for the error to appear. Ultimately, my workaround has always been to reformulate the problem somewhat until the problem disappears, but that's a rather unsatisfactory way of going about things :)

**Comment by Dekker1** [comment] 2017-10-04 06:01
This issue is being closed in a cleanup of our GitHub repository. It seems it
has been fully discussed to not be an (compiler) issue, already solved, or no
longer relevant.

If this not be the case, feel free to comment below and we'll reconsider the
issue again.

**Comment by dimbleby** [comment] 2017-10-04 08:04
So far as I know this is still broken, though I haven't got a trunk build to test on.  (But I suppose if you knew that this was fixed on trunk, you'd have said so!)

I suppose you have a test suite?  Suggest WIBNI to turn my gist into a testcase.  If it is fixed then great, you've got a new testcase that will stop anyone from breaking it again.  If it is not fixed, well know you know.

**Comment by Dekker1** [comment] 2017-10-04 10:34
My apologies, I thought the problem was located within the solver, but it is indeed a problem within the linear MiniZinc library.

Thank you for you message/correction.

**Comment by glebbelov** [comment] 2017-10-05 04:26
The problem seems in the flattening of if-then-else, because the equivalent constraint

```
constraint forall (g in Gang)
    (points[g] = [ 0,
                   let { var int: sold_out = sum (i in members(g))
                                             (bool2int(interview[i] > interview[leader(g)])) }
                   in sold_out ] [leader_cracks(g)]);

```

works. Personally I avoid variable if-conditions

**Comment by guidotack** [comment] 2017-10-06 06:28
The problem is not so much the variable if-then-else, but the let expression (for which we currently can't compute proper bounds). I'll put this on our todo list.

**Comment by glebbelov** [comment] 2017-10-09 01:21
But the alternative has the same let expression... (could just take the sum by the way)

**Comment by glebbelov** [comment] 2017-10-13 05:40
Ops, when using boolean as index, should add 1:

```
% Give points for interviewing a leader if he cracks, else don't.
constraint forall (g in Gang)
    (points[g] = [ 0,
                   let { var int: sold_out = sum (i in members(g))
                                             (bool2int(interview[i] > interview[leader(g)])) }
                   in sold_out ] [ leader_cracks(g) + 1 ]);

```

**Closed** 2023-05-19 01:06 UTC
Labels: bug
