### ISSUE TITLE
Build fails:  error: indirection requires pointer operand ('void' invalid), etc

### ISSUE THREAD

**Issue by yurivict** [MiniZinc/libminizinc#401] opened 2020-08-10 02:09 UTC
```
parser.tab.cpp:5176:3: error: member reference type 'MiniZinc::ParserLocation *' is a pointer; did you mean to use '->'?
  YYLLOC_DEFAULT (*yylsp, yyerror_range, 2);
  ^                ~~~~~
parser.tab.cpp:97:10: note: expanded from macro 'YYLLOC_DEFAULT'
  Current.filename(Rhs[1].filename()); \
  ~~~~~~~^
parser.tab.cpp:5176:19: error: indirection requires pointer operand ('void' invalid)
  YYLLOC_DEFAULT (*yylsp, yyerror_range, 2);
  ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
parser.tab.cpp:97:3: note: expanded from macro 'YYLLOC_DEFAULT'
  Current.filename(Rhs[1].filename()); \
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
parser.tab.cpp:5176:3: error: member reference type 'MiniZinc::ParserLocation *' is a pointer; did you mean to use '->'?
  YYLLOC_DEFAULT (*yylsp, yyerror_range, 2);
  ^                ~~~~~
parser.tab.cpp:98:10: note: expanded from macro 'YYLLOC_DEFAULT'
  Current.first_line(Rhs[1].first_line()); \
  ~~~~~~~^
parser.tab.cpp:5176:19: error: indirection requires pointer operand ('void' invalid)
  YYLLOC_DEFAULT (*yylsp, yyerror_range, 2);
  ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
parser.tab.cpp:98:3: note: expanded from macro 'YYLLOC_DEFAULT'
  Current.first_line(Rhs[1].first_line()); \
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
parser.tab.cpp:5176:3: error: member reference type 'MiniZinc::ParserLocation *' is a pointer; did you mean to use '->'?
  YYLLOC_DEFAULT (*yylsp, yyerror_range, 2);
  ^                ~~~~~
parser.tab.cpp:99:10: note: expanded from macro 'YYLLOC_DEFAULT'
  Current.first_column(Rhs[1].first_column()); \
  ~~~~~~~^
parser.tab.cpp:5176:19: error: indirection requires pointer operand ('void' invalid)
  YYLLOC_DEFAULT (*yylsp, yyerror_range, 2);
  ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
parser.tab.cpp:99:3: note: expanded from macro 'YYLLOC_DEFAULT'
  Current.first_column(Rhs[1].first_column()); \
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
parser.tab.cpp:5176:3: error: member reference type 'MiniZinc::ParserLocation *' is a pointer; did you mean to use '->'?
  YYLLOC_DEFAULT (*yylsp, yyerror_range, 2);
  ^                ~~~~~
parser.tab.cpp:100:10: note: expanded from macro 'YYLLOC_DEFAULT'
  Current.last_line(Rhs[N].last_line()); \
  ~~~~~~~^
parser.tab.cpp:5176:19: error: indirection requires pointer operand ('void' invalid)
  YYLLOC_DEFAULT (*yylsp, yyerror_range, 2);
  ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
parser.tab.cpp:100:3: note: expanded from macro 'YYLLOC_DEFAULT'
  Current.last_line(Rhs[N].last_line()); \
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
parser.tab.cpp:5176:3: error: member reference type 'MiniZinc::ParserLocation *' is a pointer; did you mean to use '->'?
  YYLLOC_DEFAULT (*yylsp, yyerror_range, 2);
  ^                ~~~~~
parser.tab.cpp:101:10: note: expanded from macro 'YYLLOC_DEFAULT'
  Current.last_column(Rhs[N].last_column());
  ~~~~~~~^
parser.tab.cpp:5176:19: error: indirection requires pointer operand ('void' invalid)
  YYLLOC_DEFAULT (*yylsp, yyerror_range, 2);
  ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
parser.tab.cpp:101:3: note: expanded from macro 'YYLLOC_DEFAULT'
  Current.last_column(Rhs[N].last_column());
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
10 errors generated.
```

FreeBSD 12.1
bison-3.6.4
clang-9

**Comment by Dekker1** [comment] 2020-08-10 03:09
This issue is a duplicate of https://github.com/MiniZinc/libminizinc/issues/389

This issue has already been resolved on the `develop` branch.

**Closed by Dekker1** 2020-08-10 03:09 UTC
