### ISSUE TITLE
JSON input bug, record type-inst error with enumerated type

### ISSUE THREAD

**Issue by CervEdin** [MiniZinc/libminizinc#819] opened 2024-06-17 15:40 UTC
Using a nested record with an enumerated type as a member fails when using JSON input.

model.mzn
------------
```zinc
type foo = record( bar: bar );
type bar = record( biz: biz );
enum biz = {A};
foo: input;
```

input.json
-----------
```json
{
  "input": {
    "bar" : { "biz": { "e": "A" } }
  }
}
```

output
--------
```text
MiniZinc:
type error: cannot determine coercion from type record(string: e) to type biz
```

Link to [MiniZinc playground](https://play.minizinc.dev/#project=%7B%22files%22%3A%5B%7B%22name%22%3A%22model.mzn%22%2C%22contents%22%3A%22type%20foo%20%3D%20record(%20bar%3A%20bar%20)%3B%5Cntype%20bar%20%3D%20record(%20biz%3A%20biz%20)%3B%5Cnenum%20biz%20%3D%20%7BA%7D%3B%5Cn%5Cnfoo%3A%20input%3B%22%7D%2C%7B%22name%22%3A%22input.json%22%2C%22contents%22%3A%22%7B%5Cn%20%20%5C%22input%5C%22%3A%20%7B%5Cn%20%20%20%20%5C%22bar%5C%22%20%3A%20%7B%20%5C%22biz%5C%22%3A%20%7B%20%5C%22e%5C%22%3A%20%5C%22A%5C%22%20%7D%20%7D%5Cn%20%20%7D%5Cn%7D%22%7D%5D%2C%22tab%22%3A0%2C%22solverId%22%3A%22org.minizinc.gecode_presolver%22%2C%22solverConfig%22%3A%7B%22enableTimeLimit%22%3Afalse%2C%22timeLimit%22%3A1%2C%22allSolutions%22%3Afalse%2C%22verboseCompilation%22%3Afalse%2C%22verboseSolving%22%3Afalse%2C%22compilerStatistics%22%3Afalse%2C%22solvingStatistics%22%3Afalse%2C%22outputTime%22%3Afalse%2C%22freeSearch%22%3Afalse%7D%2C%22minizincVersion%22%3A%22latest%22%7D)

**Comment by CervEdin** [comment] 2024-06-17 15:52
Seems to only be an issue when using declared types

fails.mzn
---------
```zinc
type bar = record(
  biz: biz
);
enum biz = {A};

record(
  bar: bar
): input;
```

succeeds.mzn
---------------
```zinc
enum biz = {A};

record(
  record(
    biz: biz
  ): bar
): input;
```

**Comment by CervEdin** [comment] 2024-06-17 15:58
actually it seems to be an issue just using type-inst with enumerated types

```
enum biz = {A};
type bar = record(biz: biz);

bar: input;
```

with
```json
{
  "input": {
    "biz": { "e": "A" }
  }
}
```

**Comment by CervEdin** [comment] 2024-06-17 16:00
maybe this is just a dupe of #739

**Comment by Dekker1** [comment] 2024-06-19 07:37
I believe this is indeed a duplicate of #739

**Closed by Dekker1** 2024-06-19 07:37 UTC
